name: Clojure CI

on: push

jobs:
  clojure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest
          clj-kondo: latest
          cljfmt: latest

      - name: Check format lab2
        run: cljfmt check

      - name: Lint lab2
        run: clj-kondo --lint src/lab2

      - name: Test Lab2
        run: clojure -X:test